management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
      username: Host1
      password: Oldreserve12#
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update